---
to: <%= shortname %>/ZScript.zs.temp
sh: "(if exist <%= shortname %>/ZScript.zs (rm <%= shortname %>/ZScript.zs)) && echo // DO NOT MODIFY! Automatically generated by <%= shortname %>-compile.bat at %DATE% - %TIME% >> <%= shortname %>/ZScript.zs && type <%= shortname %>\\ZScript.zs.temp >> <%= shortname %>\\ZScript.zs && rm <%= shortname %>/ZScript.zs.temp"
---
version "<%= zscript.version %>"
<% for (var i = 0; i < scripts.length; i++) { %>#include "<%= scripts[i] %>"
<% } %>